### PR TITLE
replace slows down rule engine

### PR DESCRIPTION
**Pull request by gregoryrinaldi**
query from  250ms to 15ms

### CODE REVIEW

**Review by stainii — COMMENTED** [review]
I see removal of functionality. While this could gain you some miliseconds, isn't this functionality needed?

Also, you've checked in binary files?

**Comment by peerik** [comment]
This might affect functionality when querying by UUID's.

Can you remove the binary files? I can't checkout this branch due to them.

**Comment by gregoryrinaldi** [comment]
I understand your concern but this query is not the way it should be done. It replaces all CFR's in the table. You should save the CFR in the correct format there is only one format or do it on the front-end with the incoming argument. This has a huge impact on the evaluation of FishingActivities.

**Comment by gregoryrinaldi** [comment]
Ok so I removed the binaries. Everyone one to keep this query like that?

**Comment by gregoryrinaldi** [comment]
Can we not do something on PrePersist or preUpdate?

**Comment by gregoryrinaldi** [comment]
Is it because of legacy data?

**Comment by peerik** [comment]
This test shows that the change breaks guid query.

Not sure what you mean with the CFR. Is it modified when saved?

**Pull request closed without merging**
